### ISSUE TITLE
Request:  add recursive delete

### ISSUE THREAD

**Issue by dinoshauer** [crosbymichael/zkctl#1]
Hello!

Trying out `zkctl` for a bit, but I'm stumped by the fact that recursive deletion seems to be missing or is it just me? :)

:+1: for the project!

**Comment by crosbymichael** [comment]
It's not you, it's missing ;)

**Comment by crosbymichael** [comment]
This is fixed in master along with adding watches

**Comment by dinoshauer** [comment]
Awesome! Thanks :)
